### ISSUE TITLE
Question. Missing Assets/toxigineSkull_.png

### ISSUE THREAD

**Issue by zak-ken** [yoyoberenguer/MultiplayerGameEngine#1]
* From Textures.py:200
-> SKULL = pygame.image.load('Assets\\toxigineSkull_.png').convert()

> The following file cannot be found Assets/toxigineSkull_.png

**Comment by yoyoberenguer** [comment]
Thanks for reporting an issue, 
The file toxigineSkull_.png is now present in the Asset directory. 
Download this file to your local Asset directory. 
Rgds
